# Q1

In [5]:
import numpy as np

# 1. 使用arange创建1到12的一维数组
arr = np.arange(1, 13)  # 注意arange是左闭右开，所以结束值写13

# 2. reshape成3行4列的二维数组
arr_2d = arr.reshape(3, 4)

# 3. 分别打印维度(ndim)、形状(shape)、元素总个数(size)
print("数组的维度(ndim):", arr_2d.ndim)
print("数组的形状(shape):", arr_2d.shape)
print("数组的元素总个数(size):", arr_2d.size)

数组的维度(ndim): 2
数组的形状(shape): (3, 4)
数组的元素总个数(size): 12


# Q2

In [6]:
import numpy as np

# 创建包含浮点数的NumPy数组
float_arr = np.array([1.5, 2.6, 3.7, 4.8])
print("转换前的数组：", float_arr)
print("转换前的数据类型名称：", float_arr.dtype.name)

# 使用astype转换为32位整数
int_arr = float_arr.astype(np.int32)
print("转换后的数组：", int_arr)
print("转换后的数据类型名称：", int_arr.dtype.name)


转换前的数组： [1.5 2.6 3.7 4.8]
转换前的数据类型名称： float64
转换后的数组： [1 2 3 4]
转换后的数据类型名称： int32


In [18]:
conda install pandas

^C

Note: you may need to restart the kernel to use updated packages.


3 channel Terms of Service accepted
Channels:
 - defaults
Platform: win-64
Solving environment: done

# All requested packages already installed.





==> WARNING: A newer version of conda exists. <==
    current version: 26.1.1
    latest version: 26.5.0

Please update conda by running

    $ conda update -n base -c defaults conda




# Q3

In [8]:
import numpy as np

# 创建二维数组
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 切片操作：前两行（0、1行），第2到第3列（索引1、2列）
sub_arr = arr[0:2, 1:3]

print(sub_arr)


[[2 3]
 [6 7]]


# Q4

In [9]:
import numpy as np

# 给定的一维数组
arr = np.array([10, 15, 20, 25, 30, 35])

# 1. 花式索引提取第1、3、5个元素（索引为0,2,4）
fancy_index = arr[[0, 2, 4]]
print("花式索引结果：", fancy_index)

# 2. 布尔索引提取所有大于20的元素
bool_index = arr[arr > 20]
print("布尔索引结果：", bool_index)


花式索引结果： [10 20 30]
布尔索引结果： [25 30 35]


# Q5

In [10]:
import numpy as np

# 创建形状为(3,4)的全0数组
arr_a = np.zeros((3, 4))
# 创建一维数组
arr_b = np.array([1, 2, 3, 4])

# 利用广播机制相加
result = arr_a + arr_b

# 打印结果
print(result)


[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


# Q6

In [11]:
import numpy as np

# 给定数组
x = np.array([1, 4, 9, 16])
y = np.array([2, 1, 4, 5])

# 1. 计算x中每个元素的平方根
sqrt_x = np.sqrt(x)
print("x的平方根数组：", sqrt_x)

# 2. 结合两个数组，取对应位置的最大值
result = np.maximum(sqrt_x, y)
print("对应位置的最大值：", result)


x的平方根数组： [1. 2. 3. 4.]
对应位置的最大值： [2. 2. 4. 5.]


In [17]:
np.sqrt(y)

array([1.41421356, 1.        , 2.        , 2.23606798])

# Q7

In [12]:
import numpy as np

# 创建形状为(2, 3, 4)的三维数组
arr = np.arange(24).reshape((2, 3, 4))

# 使用transpose()方法转换轴顺序为(1, 0, 2)
transposed_arr = arr.transpose((1, 0, 2))

# 打印转换后新数组的形状
print(transposed_arr.shape)


(3, 2, 4)


# Q8

In [21]:
import numpy as np

arr_x = np.array([1, 5, 7])
arr_y = np.array([2, 6, 8])
dot(arr_x,arr_y)
arr_con = np.array([True, False, True])

# 条件为True取arr_x，条件为False取arr_y
result = np.where(arr_con, arr_x, arr_y)
print(result)


NameError: name 'dot' is not defined

# Q9

In [14]:
import numpy as np

# 创建二维数组
arr = np.array([[6, 2, 7], [3, 6, 2], [4, 3, 2]])

# 1. 计算所有元素的算术平均值
mean_val = arr.mean()
print("算术平均值：", mean_val)

# 2. 沿 axis=0（列方向）排序
arr.sort(axis=0)
print("排序后的数组：")
print(arr)


算术平均值： 3.888888888888889
排序后的数组：
[[3 2 2]
 [4 3 2]
 [6 6 7]]


In [15]:
arr.mean(axis=1)

array([2.33333333, 3.        , 6.33333333])

# Q10

In [16]:
import numpy as np

# 1. 设置随机数种子
np.random.seed(10)

# 2. 生成两个形状为(2, 2)的随机矩阵A和B
A = np.random.rand(2, 2)
B = np.random.rand(2, 2)

# 3. 计算矩阵A和B的点积
dot_product = np.dot(A, B)

# （可选）打印结果验证
print("矩阵A：")
print(A)
print("矩阵B：")
print(B)
print("矩阵点积结果：")
print(dot_product)


矩阵A：
[[0.77132064 0.02075195]
 [0.63364823 0.74880388]]
矩阵B：
[[0.49850701 0.22479665]
 [0.19806286 0.76053071]]
矩阵点积结果：
[[0.38861894 0.18917279]
 [0.46418833 0.71193035]]
